services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    Random\Randomizer: ~

    Intervention\Image\Drivers\Gd\Driver: ~
    Intervention\Image\ImageManager:
        arguments:
            $driver: '@Intervention\Image\Drivers\Gd\Driver'
